services:
  mariadb:
    container_name: mariadb_maeon
    image: mariadb
    restart: always
    ports:
      - 9906:3306
    environment:
      MARIADB_ROOT_PASSWORD: ROOT_PASSWORD
      MARIADB_USER: username
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: maeon_db
      TZ: 'Asia/Bangkok'
    volumes:
      - ./mariadb/data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin_maeon
    image: phpmyadmin
    restart: always
    ports:
      - 8888:80
    environment:
      PMA_HOST: mariadb
    depends_on:
      - mariadb
